#logging:
#  level:
#    root: DEBUG
spring:
  application:
    name: Bitri-Projects-Dash
  datasource:
    url: jdbc:postgresql://localhost:5432/bpd
    username: bitri
    password: bitri
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db.changelog-master.xml
    drop-first: false
    enabled: true
    default-schema: public
    liquibase-schema: public



application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000